packages:
  - apps/*

allowBuilds:
  '@tailwindcss/oxide': true
  core-js: false
  esbuild: true
  spawn-sync: true
  vue-demi: true

catalogs:
  build:
    '@rollup/plugin-babel': ^6.0.4
    rolldown-vite: 7.3.0
    tsdown: 0.16.1
  cli:
    '@changesets/changelog-github': 0.6.0
    '@changesets/cli': 2.30.0
  dev:
    '@babel/core': ^7.26.0
    '@babel/plugin-transform-runtime': 7.28.3
    '@babel/preset-env': 7.28.3
    '@babel/preset-typescript': ^7.27.1
    '@tailwindcss/vite': ^4.1.13
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/tsconfig': ^0.8.1
    cac: ^6.7.14
    chrome-types: 0.1.321
    tailwindcss: ^4.1.13
    typescript: ^5.8.3
  lint:
    '@eslint/js': ^9.27.0
    eslint: ^9.27.0
    husky: ^9.1.7
    lint-staged: ^16.1.0
    prettier: ^3.3.3
    typescript-eslint: ^8.32.1
  markdown:
    mdast-util-to-markdown: ^2.1.2
  monorepo:
    turbo: 2.5.8
  node:
    '@babel/preset-env': ^7.26.0
    execa: ^9.5.1
    glob: ^10.4.5
  prod:
    '@babel/runtime': 7.28.3
    core-js: 3.36.0
    es-toolkit: 1.39.10
    hast-util-to-html: ^9.0.5
    lucide-vue-next: ^0.544.0
    mdast-util-gfm-strikethrough: ^2.0.0
    mdast-util-gfm-task-list-item: ^2.0.0
    mdast-util-math: ^3.0.0
    mdast-util-to-hast: ^13.2.0
    serialize-error: ^12.0.0
    tslib: ^2.8.1
    vue: ^3.5.22
  tools:
    vue-tsc: ^3.1.0
    web-ext: 10.0.0
  types:
    '@types/hast': ^3.0.4
    '@types/lodash-es': ^4.17.12
    '@types/mdast': ^4.0.4
    '@types/node': 22.12.0
    '@types/regexp.escape': 2.0.0
  utils:
    regexp.escape: 2.0.1
